apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: demo-infra-azure
  labels:
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: demo.localdev.io/v1alpha1
    kind: XDemoInfra
  resources:
    - name: storage-account
      base:
        apiVersion: storage.azure.upbound.io/v1beta1
        kind: Account
        spec:
          forProvider:
            accountTier: Standard
            accountReplicationType: LRS
            accountKind: StorageV2
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.location
          toFieldPath: spec.forProvider.location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageAccountName
          toFieldPath: metadata.annotations[crossplane.io/external-name]

    - name: storage-container
      base:
        apiVersion: storage.azure.upbound.io/v1beta1
        kind: Container
        spec:
          forProvider:
            containerAccessType: private
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageAccountName
          toFieldPath: spec.forProvider.storageAccountNameRef.name
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s"

    - name: virtual-network
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: VirtualNetwork
        spec:
          forProvider:
            addressSpace:
              - "10.0.0.0/16"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.location
          toFieldPath: spec.forProvider.location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.vnetAddressSpace
          toFieldPath: spec.forProvider.addressSpace[0]

    - name: subnet
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            addressPrefixes:
              - "10.0.1.0/24"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.subnetAddressPrefix
          toFieldPath: spec.forProvider.addressPrefixes[0]
